CREATE TABLE ADM_ACESSO_PERMISSAO (
 id_permissao INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 nome VARCHAR(10)
);

ALTER TABLE ADM_ACESSO_PERMISSAO ADD CONSTRAINT PK_ADM_ACESSO_PERMISSAO PRIMARY KEY (id_permissao);


CREATE TABLE ADM_ACESSO_ROLE (
 id_role INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 nome VARCHAR(40)
);

ALTER TABLE ADM_ACESSO_ROLE ADD CONSTRAINT PK_ADM_ACESSO_ROLE PRIMARY KEY (id_role);


CREATE TABLE CORP_EMPRESA (
 id_empresa INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 nome VARCHAR(50),
 nomeFantasia VARCHAR(50),
 cnpj CHAR(14)
);

ALTER TABLE CORP_EMPRESA ADD CONSTRAINT PK_CORP_EMPRESA PRIMARY KEY (id_empresa);


CREATE TABLE CORP_ESCOLA (
 id_escola INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 nome VARCHAR(250),
 nome_diretor VARCHAR(250)
);

ALTER TABLE CORP_ESCOLA ADD CONSTRAINT PK_CORP_ESCOLA PRIMARY KEY (id_escola);


CREATE TABLE CORP_REGIONAL (
 id_regional INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 nome CHAR(20) NOT NULL
);

ALTER TABLE CORP_REGIONAL ADD CONSTRAINT PK_CORP_REGIONAL PRIMARY KEY (id_regional);


CREATE TABLE CORP_TP_CONTATO (
 id_tipoContato INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 descricao VARCHAR(20)
);

ALTER TABLE CORP_TP_CONTATO ADD CONSTRAINT PK_CORP_TP_CONTATO PRIMARY KEY (id_tipoContato);


CREATE TABLE CORP_TP_ENDERECO (
 id_TipoEndereco INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 descricao VARCHAR(20)
);

ALTER TABLE CORP_TP_ENDERECO ADD CONSTRAINT PK_CORP_TP_ENDERECO PRIMARY KEY (id_TipoEndereco);


CREATE TABLE CORP_TP_LOGRADOURO (
 id_TipoLogradouro INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 descricao VARCHAR(20) NOT NULL
);

ALTER TABLE CORP_TP_LOGRADOURO ADD CONSTRAINT PK_CORP_TP_LOGRADOURO PRIMARY KEY (id_TipoLogradouro);


CREATE TABLE CORP_UF (
 id_uf INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 nome VARCHAR(10),
 sigla CHAR(2)
);

ALTER TABLE CORP_UF ADD CONSTRAINT PK_CORP_UF PRIMARY KEY (id_uf);


CREATE TABLE INSP_INSPECAO_NUTRICAO (
 id_inspecaoNutricao INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 observacao VARCHAR(250),
 pergunta_01 CHAR(10),
 pergunta_02 CHAR(10)
);

ALTER TABLE INSP_INSPECAO_NUTRICAO ADD CONSTRAINT PK_INSP_INSPECAO_NUTRICAO PRIMARY KEY (id_inspecaoNutricao);


CREATE TABLE  ADM_ACESSO_ROLE_PERMISSAO (
 id_role_permissao INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 id_permissao INT NOT NULL,
 id_role INT NOT NULL
);

ALTER TABLE  ADM_ACESSO_ROLE_PERMISSAO ADD CONSTRAINT PK_ ADM_ACESSO_ROLE_PERMISSAO PRIMARY KEY (id_role_permissao);


CREATE TABLE CORP_CIDADE (
 id_cidade INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 nome VARCHAR(50),
 fk_id_uf INT NOT NULL
);

ALTER TABLE CORP_CIDADE ADD CONSTRAINT PK_CORP_CIDADE PRIMARY KEY (id_cidade);


CREATE TABLE CORP_DEPARTAMENTO (
 id_departamento INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 codDepartamento VARCHAR(10) NOT NULL,
 nome CHAR(50),
 fk_id_empresa INT NOT NULL
);

ALTER TABLE CORP_DEPARTAMENTO ADD CONSTRAINT PK_CORP_DEPARTAMENTO PRIMARY KEY (id_departamento);


CREATE TABLE CORP_BAIRRO (
 id_bairro INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 nome VARCHAR(50),
 fk_id_cidade INT
);

ALTER TABLE CORP_BAIRRO ADD CONSTRAINT PK_CORP_BAIRRO PRIMARY KEY (id_bairro);


CREATE TABLE CORP_CARGO (
 id_cargo INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 descricao CHAR(10),
 fk_id_departamento INT NOT NULL
);

ALTER TABLE CORP_CARGO ADD CONSTRAINT PK_CORP_CARGO PRIMARY KEY (id_cargo);


CREATE TABLE CORP_FUNCIONARIO (
 id_funcionario INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 nome VARCHAR(50),
 dataNascimento DATE,
 cpf VARCHAR(11),
 tituloEleitor CHAR(10),
 zonaEleitoral CHAR(10),
 secao CHAR(10),
 pis VARCHAR(10),
 cnh VARCHAR(10),
 fk_id_cargo INT NOT NULL,
 observacoes VARCHAR(250),
 fk_id_escola INT NOT NULL
);

ALTER TABLE CORP_FUNCIONARIO ADD CONSTRAINT PK_CORP_FUNCIONARIO PRIMARY KEY (id_funcionario);


CREATE TABLE INSP_INSPECAO (
 id_inpecao INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 fk_id_escola INT NOT NULL,
 fk_id_inspecaoNutricao INT NOT NULL,
 data_inspecao DATE,
 fk_id_funcionario INT
);

ALTER TABLE INSP_INSPECAO ADD CONSTRAINT PK_INSP_INSPECAO PRIMARY KEY (id_inpecao);


CREATE TABLE ADM_ACESSO_USUARIO (
 id_usuario INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 nome_usuario VARCHAR(40),
 senha VARCHAR(40),
 ativo SMALLINT,
 data_criacao DATE,
 data_modificacao DATE,
 id_funcionario INT NOT NULL
);

ALTER TABLE ADM_ACESSO_USUARIO ADD CONSTRAINT PK_ADM_ACESSO_USUARIO PRIMARY KEY (id_usuario);


CREATE TABLE ADM_ACESSO_USUARIO_ROLE (
 id_usuario_role INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 id_usuario INT NOT NULL,
 id_role INT NOT NULL
);

ALTER TABLE ADM_ACESSO_USUARIO_ROLE ADD CONSTRAINT PK_ADM_ACESSO_USUARIO_ROLE PRIMARY KEY (id_usuario_role);


CREATE TABLE CORP_CONTATO (
 id_contato INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 id_tipoContato INT NOT NULL,
 descricao VARCHAR(10),
 fk_id_empresa INT NOT NULL,
 fk_id_escola INT,
 fk_id_funcionario INT
);

ALTER TABLE CORP_CONTATO ADD CONSTRAINT PK_CORP_CONTATO PRIMARY KEY (id_contato);


CREATE TABLE CORP_ENDERECO (
 id_endereco INT NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
 fk_id_bairro INT NOT NULL,
 fk_id_uf INT NOT NULL,
 cep CHAR(10),
 complemento VARCHAR(10),
 numero CHAR(10),
 logradouro VARCHAR(50),
 pontoReferencia VARCHAR(20),
 fk_id_tipo_logradouro INT NOT NULL,
 fk_id_tipo_endereco INT,
 fk_id_regional INT NOT NULL,
 fk_id_cidade INT,
 fk_id_empresa INT NOT NULL,
 fk_id_escola INT NOT NULL,
 fk_id_funcionario INT
);

ALTER TABLE CORP_ENDERECO ADD CONSTRAINT PK_CORP_ENDERECO PRIMARY KEY (id_endereco);
ALTER TABLE  ADM_ACESSO_ROLE_PERMISSAO ADD CONSTRAINT FK_ ADM_ACESSO_ROLE_PERMISSAO_0 FOREIGN KEY (id_permissao) REFERENCES ADM_ACESSO_PERMISSAO (id_permissao);
ALTER TABLE  ADM_ACESSO_ROLE_PERMISSAO ADD CONSTRAINT FK_ ADM_ACESSO_ROLE_PERMISSAO_1 FOREIGN KEY (id_role) REFERENCES ADM_ACESSO_ROLE (id_role);
ALTER TABLE CORP_CIDADE ADD CONSTRAINT FK_CORP_CIDADE_0 FOREIGN KEY (fk_id_uf) REFERENCES CORP_UF (id_uf);
ALTER TABLE CORP_DEPARTAMENTO ADD CONSTRAINT FK_CORP_DEPARTAMENTO_0 FOREIGN KEY (fk_id_empresa) REFERENCES CORP_EMPRESA (id_empresa);
ALTER TABLE CORP_BAIRRO ADD CONSTRAINT FK_CORP_BAIRRO_0 FOREIGN KEY (fk_id_cidade) REFERENCES CORP_CIDADE (id_cidade);
ALTER TABLE CORP_CARGO ADD CONSTRAINT FK_CORP_CARGO_0 FOREIGN KEY (fk_id_departamento) REFERENCES CORP_DEPARTAMENTO (id_departamento);
ALTER TABLE CORP_FUNCIONARIO ADD CONSTRAINT FK_CORP_FUNCIONARIO_0 FOREIGN KEY (fk_id_cargo) REFERENCES CORP_CARGO (id_cargo);
ALTER TABLE CORP_FUNCIONARIO ADD CONSTRAINT FK_CORP_FUNCIONARIO_1 FOREIGN KEY (fk_id_escola) REFERENCES CORP_ESCOLA (id_escola);
ALTER TABLE INSP_INSPECAO ADD CONSTRAINT FK_INSP_INSPECAO_0 FOREIGN KEY (fk_id_escola) REFERENCES CORP_ESCOLA (id_escola);
ALTER TABLE INSP_INSPECAO ADD CONSTRAINT FK_INSP_INSPECAO_1 FOREIGN KEY (fk_id_inspecaoNutricao) REFERENCES INSP_INSPECAO_NUTRICAO (id_inspecaoNutricao);
ALTER TABLE INSP_INSPECAO ADD CONSTRAINT FK_INSP_INSPECAO_2 FOREIGN KEY (fk_id_funcionario) REFERENCES CORP_FUNCIONARIO (id_funcionario);
ALTER TABLE ADM_ACESSO_USUARIO ADD CONSTRAINT FK_ADM_ACESSO_USUARIO_0 FOREIGN KEY (id_funcionario) REFERENCES CORP_FUNCIONARIO (id_funcionario);
ALTER TABLE ADM_ACESSO_USUARIO_ROLE ADD CONSTRAINT FK_ADM_ACESSO_USUARIO_ROLE_0 FOREIGN KEY (id_usuario) REFERENCES ADM_ACESSO_USUARIO (id_usuario);
ALTER TABLE ADM_ACESSO_USUARIO_ROLE ADD CONSTRAINT FK_ADM_ACESSO_USUARIO_ROLE_1 FOREIGN KEY (id_role) REFERENCES ADM_ACESSO_ROLE (id_role);
ALTER TABLE CORP_CONTATO ADD CONSTRAINT FK_CORP_CONTATO_0 FOREIGN KEY (id_tipoContato) REFERENCES CORP_TP_CONTATO (id_tipoContato);
ALTER TABLE CORP_CONTATO ADD CONSTRAINT FK_CORP_CONTATO_1 FOREIGN KEY (fk_id_empresa) REFERENCES CORP_EMPRESA (id_empresa);
ALTER TABLE CORP_CONTATO ADD CONSTRAINT FK_CORP_CONTATO_2 FOREIGN KEY (fk_id_escola) REFERENCES CORP_ESCOLA (id_escola);
ALTER TABLE CORP_CONTATO ADD CONSTRAINT FK_CORP_CONTATO_3 FOREIGN KEY (fk_id_funcionario) REFERENCES CORP_FUNCIONARIO (id_funcionario);
ALTER TABLE CORP_ENDERECO ADD CONSTRAINT FK_CORP_ENDERECO_0 FOREIGN KEY (fk_id_bairro) REFERENCES CORP_BAIRRO (id_bairro);
ALTER TABLE CORP_ENDERECO ADD CONSTRAINT FK_CORP_ENDERECO_1 FOREIGN KEY (fk_id_uf) REFERENCES CORP_UF (id_uf);
ALTER TABLE CORP_ENDERECO ADD CONSTRAINT FK_CORP_ENDERECO_2 FOREIGN KEY (fk_id_tipo_logradouro) REFERENCES CORP_TP_LOGRADOURO (id_TipoLogradouro);
ALTER TABLE CORP_ENDERECO ADD CONSTRAINT FK_CORP_ENDERECO_3 FOREIGN KEY (fk_id_tipo_endereco) REFERENCES CORP_TP_ENDERECO (id_TipoEndereco);
ALTER TABLE CORP_ENDERECO ADD CONSTRAINT FK_CORP_ENDERECO_4 FOREIGN KEY (fk_id_regional) REFERENCES CORP_REGIONAL (id_regional);
ALTER TABLE CORP_ENDERECO ADD CONSTRAINT FK_CORP_ENDERECO_5 FOREIGN KEY (fk_id_cidade) REFERENCES CORP_CIDADE (id_cidade);
ALTER TABLE CORP_ENDERECO ADD CONSTRAINT FK_CORP_ENDERECO_6 FOREIGN KEY (fk_id_empresa) REFERENCES CORP_EMPRESA (id_empresa);
ALTER TABLE CORP_ENDERECO ADD CONSTRAINT FK_CORP_ENDERECO_7 FOREIGN KEY (fk_id_escola) REFERENCES CORP_ESCOLA (id_escola);
ALTER TABLE CORP_ENDERECO ADD CONSTRAINT FK_CORP_ENDERECO_8 FOREIGN KEY (fk_id_funcionario) REFERENCES CORP_FUNCIONARIO (id_funcionario);


